apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-backend-app
spec:
  interval: 10m0s
  path: ./
  postBuild:
    substitute:
      ENVIRONMENT_NAME: feat-6
  prune: true
  sourceRef:
    kind: OCIRepository
    name: demo-backend-app
  targetNamespace: demo-app
