apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  labels:
    app.kubernetes.io/part-of: istio
spec:
  chart:
    spec:
      chart: ztunnel
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      version: "1.28.x"
  dependsOn:
  - name: istio-cni
  interval: 1h0m0s
