apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: demo-frontend-app
  namespace: sample-app-dev
spec:
  interval: 10m0s
  provider: generic
  ref:
    tag: 2ab3aba0-k8s
  url: oci://docker.io/aliktb/demo-frontend-app
