apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: demo-frontend-app
spec:
  interval: 10m0s
  provider: generic
  ref:
    tag: 4e1fc7cf-k8s
  url: oci://registry.gitlab.com/aliktb-sandbox/demo-frontend-app
